routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('micros','MicroController');

app/Micro.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Micro extends Model
{
    protected $fillable = [
        'name', 'color', 'number'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MicroController.php
<?php

namespace App\Http\Controllers;

use App\Micro;
use Illuminate\Http\Request;

class MicroController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {        
        $micros = Micro::latest()->paginate(5); 

        return view('micros.index',compact('micros'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('micros.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'color' => 'required',
            'number' => 'required',
        ]);

        Micro::create($request->all());
        return redirect()->route('micros.index')
            ->with('success','Micro created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Micro  $micro
     * @return \Illuminate\Http\Response
     */
    public function show(Micro $micro)
    {
        return view('micros.show',compact('micro'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Micro  $micro
     * @return \Illuminate\Http\Response
     */
    public function edit(Micro $micro)
    {
        return view('micros.edit',compact('micro'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Micro  $micro
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Micro $micro)
    {
        $request->validate([
            'name' => 'required',
            'color' => 'required',
            'number' => 'required',
        ]); 

        $micro->update($request->all());
        return redirect()->route('micros.index')
            ->with('success','Micro updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Micro  $micro
     * @return \Illuminate\Http\Response
     */
    public function destroy(Micro $micro)
    {
        $micro->delete();
        
        return redirect()->route('micros.index')
            ->with('success','Micro deleted successfully');
    }
}

resources/views/micros/create.blade.php
@extends('micros.layout')

  

@section('content')

<div class="row">

    <div class="col-lg-12 margin-tb">

        <div class="pull-left">

            <h2>Add New Product</h2>

        </div>

        <div class="pull-right">

            <a class="btn btn-primary" href="{{ route('micros.index') }}"> Back</a>

        </div>

    </div>

</div>

   

@if ($errors->any())

    <div class="alert alert-danger">

        <strong>Whoops!</strong> There were some problems with your input.<br><br>

        <ul>

            @foreach ($errors->all() as $error)

                <li>{{ $error }}</li>

            @endforeach

        </ul>

    </div>

@endif

   

<form action="{{ route('micros.store') }}" method="POST">

    @csrf

  

     <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name:</strong>

                <input type="text" name="name" class="form-control" placeholder="Name">

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Color:</strong>

                <textarea class="form-control" style="height:150px" name="color" placeholder="Color"></textarea>

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Number:</strong>

                <textarea class="form-control" style="height:150px" name="number" placeholder="Number"></textarea>

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

                <button type="submit" class="btn btn-primary">Submit</button>

        </div>

    </div>

   

</form>

@endsection

resources/views/micros/edit.blade.php
@extends('micros.layout')

   

@section('content')

    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Edit micro</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('micros.index') }}"> Back</a>

            </div>

        </div>

    </div>

   

    @if ($errors->any())

        <div class="alert alert-danger">

            <strong>Whoops!</strong> There were some problems with your input.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif

  

    <form action="{{ route('micros.update',$micro->id) }}" method="POST">

        @csrf

        @method('PUT')

   

         <div class="row">

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Name:</strong>

                    <input type="text" name="name" value="{{ $micro->name }}" class="form-control" placeholder="Name">

                </div>

            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Number:</strong>

                    <textarea class="form-control" style="height:150px" name="number" placeholder="Number">{{ $micro->number }}</textarea>

                </div>

            </div>
            
            <div class="col-xs-12 col-sm-12 col-md-12">

                <div class="form-group">

                    <strong>Color:</strong>

                    <textarea class="form-control" style="height:150px" name="color" placeholder="Color">{{ $micro->color }}</textarea>

                </div>

            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">

              <button type="submit" class="btn btn-primary">Submit</button>

            </div>

        </div>

   

    </form>

@endsection

resources/views/micros/index.blade.php
@extends('micros.layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Laravel 6 CRUD Example from scratch - ItSolutionStuff.com</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('micros.create') }}"> Create New micro</a>
            </div>
        </div>
    </div>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Details</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($micros as $micro)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $micro->name }}</td>
            <td>{{ $micro->color }}</td>
            <td>{{ $micro->number }}</td>
            <td>
                <form action="{{ route('micros.destroy',$micro->id) }}" method="POST">
                    <a class="btn btn-info" href="{{ route('micros.show',$micro->id) }}">Show</a>
                    <a class="btn btn-primary" href="{{ route('micros.edit',$micro->id) }}">Edit</a>
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    {!! $micros->links() !!}
@endsection

resources/views/micros/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel 6 CRUD Application - ItSolutionStuff.com</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>
<div class="container">
    @yield('content')
</div>
</body>
</html>

resources/views/micros/show.blade.php
@extends('micros.layout')

@section('content')

    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2> Show micro</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('micros.index') }}"> Back</a>

            </div>

        </div>

    </div>

   

    <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Name:</strong>

                {{ $micro->name }}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Number:</strong>

                {{ $micro->number }}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Color:</strong>

                {{ $micro->color }}

            </div>

        </div>

    </div>

@endsection